# This action uses 'dotnet format' and FAILS if the code is not already formatted.
# Run 'dotnet format' in a project or solution folder to autoformat the code.
# The 'dotnet format' command requires Windows because ScottPlot 4 requires MSBuild.
# A job summary is included which describes how to correct this issue.
# https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

name: PR Autoformat

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-format:
    name: Ensure 'dotnet format' was run
    runs-on: windows-latest
    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v3
      - name: âœ¨ Set up .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"
      - name: âœ’ï¸ Check ScottPlot4 formatting
        run: dotnet format --verify-no-changes "src/ScottPlot4/ScottPlot4.sln"
      - name: âœ’ï¸ Check ScottPlot5 formatting
        run: dotnet format --verify-no-changes "src/ScottPlot5/ScottPlot5.sln"
      - name: ðŸ’¡ Display Additional Information
        if: ${{ failure() }}
        shell: bash
        run: cat .github/workflows/autoformat-message.md >> $GITHUB_STEP_SUMMARY
