name: Test ScottPlot v4

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/ScottPlot4/**"
  pull_request:
    paths:
      - "src/ScottPlot4/**"

jobs:
  format:
    runs-on: windows-latest
    name: ‚úíÔ∏è Check Formatting
    steps:
      - name: üõí Checkout
        uses: actions/checkout@v2
      - name: ‚ú® Set up .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: ‚úíÔ∏è Set up dotnet-format
        run: dotnet tool install -g dotnet-format
      - name: üßê Check Code Format
        working-directory: src/ScottPlot4
        run: dotnet-format --check

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            osName: Linux
          - os: windows-latest
            osName: Windows
          - os: macos-latest
            osName: MacOS
    runs-on: ${{ matrix.os }}
    name: üß™ Test on ${{ matrix.osName }}
    steps:
      - name: üõí Checkout
        uses: actions/checkout@v2
      - name: ‚ú® Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: ‚ú® Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: üöö Restore
        working-directory: src/ScottPlot4/ScottPlot.Tests
        run: dotnet restore
      - name: üõ†Ô∏è Build
        working-directory: src/ScottPlot4/ScottPlot.Tests
        run: dotnet build --configuration Release
      - name: üß™ Test
        working-directory: src/ScottPlot4/ScottPlot.Tests
        run: dotnet test --configuration Release

  package:
    name: üì¶ Create NuGet Packages
    runs-on: windows-latest
    steps:
      - name: üõí Checkout
        uses: actions/checkout@v2
      - name: ‚ú® Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: üì¶ Package ScottPlot
        run: |
          dotnet restore src/ScottPlot4/ScottPlot/ScottPlot.csproj
          dotnet build src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release

      - name: üì¶ Package ScottPlot.WinForms
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --configuration Release

      - name: üì¶ Package ScottPlot.WPF
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --configuration Release

      - name: üì¶ Package ScottPlot.Avalonia
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --configuration Release

      - name: üì¶ Package ScottPlot.Eto
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj --configuration Release

  build:
    runs-on: windows-latest
    name: üõ†Ô∏è Build Entire Solution
    steps:
      - name: üõí Checkout
        uses: actions/checkout@v2
      - name: üê¢ Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: ‚ú® Set up .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true
      - name: üöö Restore
        working-directory: src/ScottPlot4
        run: dotnet restore
      - name: üêå MSBuild
        working-directory: src/ScottPlot4
        run: msbuild -property:Configuration=Release -verbosity:minimal
