name: Demo

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
      - created

jobs:
  publish:
    name: Publish Demo Apps
    if: github.event_name != 'release'
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: ğŸ¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: ğŸšš Restore WinForms Demo
        run: dotnet restore src/demo/ScottPlot.Demo.WinForms
      - name: ğŸŒ Build WinForms Demo
        run: msbuild "src/demo/ScottPlot.Demo.WinForms" -property:Configuration=Release -verbosity:minimal
      - name: ğŸ“¦ Zip WinForms Demo
        uses: thedoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d # v0.6.0
        with:
          type: "zip"
          filename: "ScottPlot-Demo-WinForms.zip"
          directory: "src/demo/ScottPlot.Demo.WinForms/bin"
      - name: ğŸ’¾ Store
        uses: actions/upload-artifact@v2
        with:
          name: ScottPlot-Demo
          retention-days: 1
          path: |
            src/demo/ScottPlot.Demo.WinForms/bin/ScottPlot-Demo-WinForms.zip
