name: Demo

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
      - created

jobs:
  winforms-demo:
    name: WinForms Demo
    runs-on: windows-latest
    env:
      CSPROJ_FOLDER: src/demo/ScottPlot.Demo.WinForms
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ğŸ¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: ğŸšš Restore
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: dotnet restore

      - name: ğŸŒ MSBuild
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: msbuild -property:Configuration=Release -verbosity:minimal

      - name: ğŸ“¦ Zip
        uses: thedoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d # v0.6.0
        with:
          working-directory: ${{ env.CSPROJ_FOLDER }}
          type: "zip"
          filename: "ScottPlot-Demo-WinForms.zip"
          directory: "bin"

      - name: ğŸ’¾ Store
        uses: actions/upload-artifact@v2
        with:
          working-directory: ${{ env.CSPROJ_FOLDER }}/bin
          name: ScottPlot-Demo
          retention-days: 1
          path: ScottPlot-Demo-WinForms.zip