name: ScottPlot 5 Developer Website

# This script builds the ScottPlot 5 cookbook
# and publishes it to dev.scottplot.net (hosted by GitHub Pages)

on:
  workflow_dispatch:
  push: # only runs on commits to main branch (typically after a merge)
    branches:
      - main
    paths:
      - "src/ScottPlot5/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    name: Cookbook
    runs-on: ubuntu-latest
    environment:
      name: Cookbook
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: ğŸ—› Download Fonts
        run: |
          wget -O open_sans.zip https://fonts.google.com/download?family=Open%20Sans
          unzip -d open_sans/ open_sans.zip
          mv open_sans /usr/share/fonts/
          fc-cache -fv
      - name: âœ¨ Set up .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: ğŸšš Restore
        run: dotnet restore "src/ScottPlot5/ScottPlot5 Cookbook"
      - name: ğŸ› ï¸ Build
        run: dotnet build "src/ScottPlot5/ScottPlot5 Cookbook" --no-restore
      - name: ğŸ§‘â€ğŸ³ Generate Cookbook
        run: dotnet test "src/ScottPlot5/ScottPlot5 Cookbook" --no-restore --verbosity minimal
      - name: ğŸ› ï¸ Configure Pages
        uses: actions/configure-pages@v2
      - name: ğŸ“¦ Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dev/www"
      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
