name: Deploy

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: windows-latest
    name: Build Packages
    steps:
      - name: üõí Checkout
        uses: actions/checkout@v2

      - name: üê¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: üõ†Ô∏è Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: ‚ú® Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: üì¶ Pack
        run: |
          dotnet pack src/ScottPlot/ScottPlot.csproj --configuration Release
          dotnet pack src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --configuration Release
          dotnet pack src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --configuration Release
          dotnet build src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --configuration Release

      - name: üíæ Store
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: |
            src\ScottPlot\bin\Release\*.nupkg
            src\controls\ScottPlot.WinForms\bin\Release\*.nupkg
            src\controls\ScottPlot.WPF\bin\Release\*.nupkg
            src\controls\ScottPlot.Avalonia\bin\Release\*.nupkg

      #  publishing only works if version number was bumped
      - name: üöÄ Publish
        run: |
          nuget push "src\ScottPlot\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          nuget push "src\controls\ScottPlot.WinForms\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          nuget push "src\controls\ScottPlot.WPF\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          nuget push "src\controls\ScottPlot.Avalonia\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
