# This workflow performs a full build of ScottPlot 5.
# It's really slow because it requires many workloads.
# It also fixes any project code formatting issues.
# It is not meant to run on PRs.

name: SP5 Full Build

on:
  workflow_dispatch:
  workflow_call:

env:
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  DOTNET_VERSION: "8.0.x"

jobs:
  full-build:
    name: Full Build
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: ğŸ¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: âœ¨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: âœ¨ Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: ğŸšš Install Workloads
        run: dotnet workload install maui-android maui-ios maccatalyst wasm-tools
      - name: ğŸšš Workload Restore
        run: dotnet workload restore "${{ env.SLN_SP5_FULL }}"
      - name: ğŸšš Solution Restore
        run: dotnet restore "${{ env.SLN_SP5_FULL }}"
      - name: ğŸ› ï¸ Full Build
        run: dotnet build "${{ env.SLN_SP5_FULL }}" --configuration Release
      - name: ğŸ§ª Run Tests
        run: dotnet test "${{ env.SLN_SP5_FULL }}" --configuration Release
