name: ScottPlot 4 Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: üöÄ Publish ScottPlot4 Packages
    runs-on: windows-latest
    steps:
      - name: üõí Checkout
        uses: actions/checkout@v3

      - name: ‚ú® Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: üõ†Ô∏è Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: üì¶ Package ScottPlot
        run: |
          dotnet restore src/ScottPlot4/ScottPlot/ScottPlot.csproj
          dotnet build src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release

      - name: üì¶ Package ScottPlot.WinForms
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WinForms
          dotnet build src/ScottPlot4/ScottPlot.WinForms --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WinForms --configuration Release

      - name: üì¶ Package ScottPlot.WPF
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WPF
          dotnet build src/ScottPlot4/ScottPlot.WPF --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WPF --configuration Release

      - name: üì¶ Package ScottPlot.Avalonia
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Avalonia
          dotnet build src/ScottPlot4/ScottPlot.Avalonia --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Avalonia --configuration Release

      - name: üì¶ Package ScottPlot.Eto
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Eto
          dotnet build src/ScottPlot4/ScottPlot.Eto --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Eto --configuration Release

      - name: üíæ Store Packages
        uses: actions/upload-artifact@v3
        with:
          name: ScottPlot-Packages
          retention-days: 1
          path: |
            src/ScottPlot4/ScottPlot/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.WinForms/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.WinForms/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.WPF/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.WPF/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.Avalonia/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.Avalonia/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.Eto/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.Eto/bin/Release/*.snupkg

      - name: üöÄ Push to NuGet
        run: |
          nuget push "src\ScottPlot4\ScottPlot\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          nuget push "src\ScottPlot4\ScottPlot.WinForms\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          nuget push "src\ScottPlot4\ScottPlot.WPF\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          nuget push "src\ScottPlot4\ScottPlot.Avalonia\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          nuget push "src\ScottPlot4\ScottPlot.Eto\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
