name: ScottPlot 4 Deploy

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  TEST_PROJECT_FOLDER: "src/ScottPlot4/ScottPlot.Tests/"

jobs:
  deploy:
    name: ğŸš€ Publish ScottPlot4 Packages
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4

      - name: âœ¨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: ğŸšš Restore Tests
        working-directory: ${{ env.TEST_PROJECT_FOLDER }}
        run: dotnet restore

      - name: ğŸ› ï¸ Build Tests
        working-directory: ${{ env.TEST_PROJECT_FOLDER }}
        run: dotnet build --configuration Release

      - name: ğŸ§ª Run Tests
        working-directory: ${{ env.TEST_PROJECT_FOLDER }}
        run: dotnet test --configuration Release --verbosity minimal

      - name: ğŸ› ï¸ Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: ğŸš€ Deploy ScottPlot
        working-directory: "src/ScottPlot4/ScottPlot/"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push .\bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: ğŸš€ Deploy ScottPlot.WinForms
        working-directory: "src/ScottPlot4/ScottPlot.WinForms"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push .\bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: ğŸš€ Deploy ScottPlot.WPF
        working-directory: "src/ScottPlot4/ScottPlot.WPF"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push .\bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: ğŸš€ Deploy ScottPlot.Avalonia
        working-directory: "src/ScottPlot4/ScottPlot.Avalonia"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push .\bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: ğŸš€ Deploy ScottPlot.Eto
        working-directory: "src/ScottPlot4/ScottPlot.Eto"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push .\bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json
