name: PR

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - src/ScottPlot5/**

concurrency:
  group: $SP5-{{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SLN_SP5_TEST: "src/ScottPlot5/ScottPlot5 Tests/ScottPlot Tests.csproj"
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  DOTNET_VERSION: "8.0.x"

jobs:
  test-linux:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: âœ¨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: ğŸšš Restore ScottPlot5
        run: dotnet restore "${{ env.SLN_SP5_TEST }}"
      - name: ğŸ› ï¸ Build ScottPlot5
        run: dotnet build "${{ env.SLN_SP5_TEST }}" --configuration Release
      - name: ğŸ§ª Test ScottPlot5
        run: dotnet test "${{ env.SLN_SP5_TEST }}" --configuration Release --verbosity minimal

  test-windows:
    needs: [test-linux]
    name: Full Build
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: ğŸ¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: âœ¨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: âœ¨ Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: ğŸšš Install Additional Workloads
        run: dotnet workload install maui-android maui-ios maccatalyst wasm-tools
      - name: ğŸšš Workload Restore ScottPlot5
        run: dotnet workload restore "${{ env.SLN_SP5_FULL }}"
      - name: ğŸšš Solution Restore ScottPlot5
        run: dotnet restore "${{ env.SLN_SP5_FULL }}"
      - name: ğŸ› ï¸ Full Build ScottPlot5
        run: dotnet build "${{ env.SLN_SP5_FULL }}" --configuration Release
      - name: âœ’ï¸ Check Code Formatting
        if: github.event_name == 'pull_request'
        run: |
          dotnet format --verify-no-changes "${{ env.SLN_SP5_FULL }}"
          echo "::warning::Run 'dotnet format ScottPlot5.sln' to fix code format errors"
      - name: âœ’ï¸ Fix Code Formatting
        if: github.event_name != 'pull_request'
        run: |
          dotnet format ${{ env.SLN_SP5_FULL }}
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git pull
          git commit -am "CI: autoformat"
          git push