name: PR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - src/ScottPlot5/**

env:
  SLN_SP5_TEST: "src/ScottPlot5/ScottPlot5-tests.slnf"
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  DOTNET_VERSION: "7.0.x"

jobs:
  test-linux:
    name: ScottPlot5 Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: âœ¨ Setup .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: ğŸšš Restore
        run: dotnet restore ${{env.SLN_SP5_TEST}}
      - name: ğŸ› ï¸ Build
        run: dotnet build ${{env.SLN_SP5_TEST}} --configuration Release
      - name: ğŸ§ª Test
        run: dotnet test ${{env.SLN_SP5_TEST}} --configuration Release --verbosity minimal
      - name: ğŸ“¦ Package
        run: dotnet pack ${{env.SLN_SP5_TEST}} --configuration Release

  test-windows:
    name: ScottPlot5 Test on Windows
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: ğŸ¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: âœ¨ Setup .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: ğŸšš Restore
        run: dotnet restore ${{env.SLN_SP5_FULL}}
      - name: ğŸ› ï¸ Build
        run: dotnet build ${{env.SLN_SP5_FULL}} --configuration Release
      - name: ğŸ§ª Test
        run: dotnet test ${{env.SLN_SP5_FULL}} --configuration Release --verbosity minimal
      - name: ğŸ“¦ Package
        run: dotnet pack ${{env.SLN_SP5_FULL}} --configuration Release

  full-build:
    name: ScottPlot5 Full Build
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: ğŸ¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: âœ¨ Setup .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: ğŸšš Restore
        run: dotnet restore ${{env.SLN_SP5_FULL}}
      - name: ğŸ› ï¸ Build
        run: dotnet build ${{env.SLN_SP5_FULL}} --configuration Release
      - name: ğŸ“¦ Package
        run: dotnet pack ${{env.SLN_SP5_FULL}} --configuration Release

  check-format:
    name: Ensure 'dotnet format' was run
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: âœ¨ Set up .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: âœ’ï¸ Check Code formatting
        run: |
          dotnet format --verify-no-changes ${{env.SLN_SP5_FULL}}
          echo "::warning::Run 'dotnet format ScottPlot5.sln' to fix code format errors"
