name: CodeQL

on:
  workflow_dispatch:

jobs:
  windows:
    name: Security Analysis
    runs-on: windows-latest
    permissions:
      security-events: write
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3
      - name: ğŸ¢ Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: âœ¨ Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: âš™ï¸ Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
      - name: ğŸšš Restore SP4
        run: dotnet restore "src/ScottPlot4"
      - name: ğŸ› ï¸ Build SP4
        run: dotnet build "src/ScottPlot4"
      - name: ğŸšš Restore SP5
        run: dotnet restore "src/ScottPlot5"
      - name: ğŸ› ï¸ Build SP5
        run: dotnet build "src/ScottPlot5"
      - name: ğŸ” Analyze
        uses: github/codeql-action/analyze@v2
