# This workflow evaluates security for code in this repository
# that lives outside the ScottPlot source folder.
# ScottPlot binaries are evaluated in workflows that build and test them.
name: "Security Analysis"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  security-scan:
    name: Non-Compiled Code Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
      - name: ğŸ›’ Checkout repository
        uses: actions/checkout@v4
      - name: âš™ï¸ Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python, javascript-typescript
      - name: ğŸ•µï¸ Analyze Python Code
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
      - name: ğŸ•µï¸ Analyze JavaScript Code
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"
